version: "3.9"

# external fixed network to share with other container instances
networks:
  javams:
    name: javams
    driver: bridge


services:

 # https://pgpedia.info/postgresql-versions/postgresql-12.html
  postgres:
    image: wktaade.azurecr.io/cache/postgres:12.15-alpine3.18
    container_name: postgres12_15_dev
    restart: on-failure:3
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Did2.PfdPU.
        POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=de_DE.UTF-8 --lc-ctype=de_DE.UTF-8
    volumes:
      - ~/.javams-container/postgres:/var/lib/postgresql/data
      - ./pginitdb.sh:/docker-entrypoint-initdb.d/init.sh:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - javams


  pgadmin:
    restart: on-failure:3
    image: wktaade.azurecr.io/cache/pgadmin4:6
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@javams.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8040:80
    volumes:
      - ~/.javams-container/pgadmin:/root/.pgadmin
      - ./pgadmin.json:/pgadmin4/servers.json:ro
    networks:
      - javams
      
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - javams
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - javams